name: go-api

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: apidb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ..
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ../.env
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: